package ca.licef.comete.vocabularies;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from oai.rdf 
 * @author Auto-generated by schemagen on 25 nov. 2013 14:52 
 */
public class OAI {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.openarchives.org/OAI/2.0/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>oai-identifier</p> */
    public static final DatatypeProperty identifier = m_model.createDatatypeProperty( "http://www.openarchives.org/OAI/2.0/oai-identifier" );
    
    /** <p>oai-datestamp</p> */
    public static final DatatypeProperty datestamp = m_model.createDatatypeProperty( "http://www.openarchives.org/OAI/2.0/oai-datestamp" );
    
}
