PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?concept ?scheme
WHERE '{'
    ?concept skos:inScheme ?scheme 
    '{' <{0}> (skos:closeMatch|skos:narrowMatch) ?concept '}'
    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:closeMatch ?child '}'
    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:narrowMatch ?child '}'
    UNION
    '{' <{0}> skos:closeMatch/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:closeMatch/skos:narrowMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowMatch/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowMatch/skos:narrowMatch ?concept '}'


    UNION
    '{' <{0}> skos:closeMatch/skos:narrowerTransitive/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:closeMatch/skos:narrowerTransitive/skos:narrowMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowMatch/skos:narrowerTransitive/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowMatch/skos:narrowerTransitive/skos:narrowMatch ?concept '}'


    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:closeMatch/skos:closeMatch ?concept '}'
    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:closeMatch/skos:narrowMatch ?concept '}'
    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:narrowMatch/skos:closeMatch ?concept '}'
    UNION    
    '{' <{0}> skos:narrowerTransitive/skos:narrowMatch/skos:narrowMatch ?concept '}'


    UNION
    '{' <{0}> skos:narrowerTransitive/skos:closeMatch/skos:narrowerTransitive/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowerTransitive/skos:closeMatch/skos:narrowerTransitive/skos:narrowMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowerTransitive/skos:narrowMatch/skos:narrowerTransitive/skos:closeMatch ?concept '}'
    UNION
    '{' <{0}> skos:narrowerTransitive/skos:narrowMatch/skos:narrowerTransitive/skos:narrowMatch ?concept '}'

    FILTER( {1} )    
'}'