PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

DELETE '{'
    ?s ?p ?o
'}'
WHERE '{'
    ?s ?p ?o .
    ?s rdf:type comete:LearningObject .
    ?s comete:hasMetadataRecord <{0}> .
    ?ctxt rdf:type comete:VocContext .
    ?ctxt comete:vocConceptLinkingPredicate ?conceptLink .
    FILTER ( ?p = dcterms:title || ?p = dcterms:description || ?p = foaf:page ||
             ?p = dcterms:creator || ?p = dcterms:publisher || ?p = dcterms:publisher ||
             ?p = comete:learningResourceType || ?p = comete:educationalLevel ||
             ?p = comete:extraInfo || ?p = dcterms:format ||
             ?p = dcterms:language || ?p = comete:keyword ||
             ?p = comete:state || ?p = ?conceptLink )
'}'
