PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT (COUNT(?s) AS ?count)
WHERE '{'
    ?s rdf:type comete:MetadataRecord .
    ?s comete:validationReportLink ?report .
    FILTER ( regex( ?report, "{0}" ) )
'}'

