PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX metamodel: <http://comete.licef.ca/metamodel#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

SELECT ?identity ?p ?org ?orgName
WHERE '{'
    <{0}> ?p ?identity .
    FILTER ( ?p = dcterms:creator || ?p = dcterms:publisher )
    OPTIONAL '{'
        ?identity org:memberOf ?org .
        OPTIONAL '{'
            ?org foaf:name ?orgName
        '}'
    '}'
'}'

