PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT ?s
WHERE '{'
    ?s rdf:type comete:LearningObject .
    ?s dcterms:language "{0}"
'}'

