'{'
    ?ctxt rdf:type comete:VocContext .
    ?ctxt comete:vocConceptLinkingPredicate ?p .
    ?ctxt comete:vocUri ?vocUri .
    <{0}> (skos:closeMatch|skos:narrowerTransitive)* ?c .
    ?c skos:inScheme ?vocUri .
    ?s ?p ?c .
    FILTER ( NOT EXISTS '{' ?c skos:narrowerTransitive <{0}> '}' )
    FILTER ( {1} )
'}'
