'{'
    ?ctxt rdf:type comete:VocContext .
    ?ctxt comete:vocConceptLinkingPredicate ?p .
    ?ctxt comete:vocUri <{1}> .
    '{' ?s ?p <{0}> '}'
    UNION
    '{' ?s ?p ?c .
        GRAPH <{1}> '{' <{0}> skos:narrowerTransitive ?c '}' '}'
'}'
