'{' (?s ?score) text:query ( dcterms:title "{0}" ) '}'
UNION
'{' (?s ?score) text:query ( dcterms:title "{0}" "lang:{1}" ) '}'
UNION
'{' (?s ?score) text:query ( dcterms:description "{0}" ) '}'
UNION
'{' (?s ?score) text:query ( dcterms:description "{0}" "lang:{1}" ) '}'
UNION
'{' (?s ?score) text:query ( comete:keyword "{0}" ) '}'
UNION
'{' (?s ?score) text:query ( comete:keyword "{0}" "lang:{1}" ) '}'
UNION
'{' (?s ?score) text:query ( comete:extraInfo "{0}" ) '}'
UNION
'{' (?s ?score) text:query ( comete:extraInfo "{0}" "lang:{1}" ) '}'
UNION
'{' (?author ?score) text:query ( foaf:name "{0}" ) .
    ?s dcterms:creator ?author '}'
UNION
'{' (?publisher ?score) text:query ( foaf:name "{0}" ) .
    ?s dcterms:publisher ?publisher  '}'
UNION
'{' (?concept ?score) text:query ( skos:prefLabel "{0}" ) .
    ?ctxt rdf:type comete:VocContext .
    ?ctxt comete:vocConceptLinkingPredicate ?conceptLink .
    ?s ?conceptLink ?concept '}'
UNION
'{' (?concept ?score) text:query ( skos:prefLabel "{0}" "lang:{1}" ) .
    ?ctxt rdf:type comete:VocContext .
    ?ctxt comete:vocConceptLinkingPredicate ?conceptLink .
    ?s ?conceptLink ?concept '}'
