'{'
    ?p{2} ^comete:vocConceptLinkingPredicate/comete:vocUri <{1}> .
    '{' ?s ?p{2} <{0}> '}'
    UNION
    '{' ?s ?p{2} ?c .
        GRAPH <{1}> '{'
            <{0}> skos:narrowerTransitive ?c .
            ?c skos:inScheme <{1}>
        '}'
    '}'
'}'
