PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT (count(DISTINCT ?s) as ?count) 
WHERE '{'
    ?s rdf:type comete:LearningObject .
    '{'
        GRAPH <server:main-fullTextView_{0}> '{'
            ?s dct:title "{1}"
        '}'
    '}'
    UNION
    '{'
        GRAPH <server:main-fullTextView_{0}> '{'
            ?s dct:description "{1}"
        '}'
    '}'
    UNION
    '{'
        GRAPH <server:main-fullTextView_{0}> '{'
            ?s comete:keyword "{1}"
        '}'
    '}'
    UNION
    '{'
        GRAPH <server:main-fullTextView_{0}> '{'
            ?s comete:extraInfo "{1}"
        '}'
    '}'
    UNION
    '{'
        ?s dct:creator ?author .
        GRAPH <server:main-fullTextView_{0}> '{'
            ?author foaf:name "{1}"
        '}'
    '}'
    UNION
    '{'
        ?s dct:publisher ?publisher .
        GRAPH <server:main-fullTextView_{0}> '{'
            ?publisher foaf:name "{1}"
        '}'
    '}'
    UNION
    '{'
        ?s dct:subject ?concept .
        GRAPH <server:voc-fullTextView_{0}> '{'
            ?concept skos:prefLabel "{1}"
        '}'
    '}'
'}'
