PREFIX text: <http://jena.apache.org/text#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT DISTINCT ?s ?location ?format ?added ?updated ?state
{0}
WHERE '{'
{1}

    ?s rdf:type comete:LearningObject .
    OPTIONAL '{'
        ?s foaf:page ?location
    '}'
    OPTIONAL '{'
        ?s dcterms:format ?format
    '}'
    OPTIONAL '{'
        ?s comete:added ?added
    '}'
    OPTIONAL '{'
        ?s comete:updated ?updated
    '}'
    OPTIONAL '{'
        ?s comete:state ?state
    '}'
    {2}
'}'
ORDER BY DESC({3})
OFFSET {4,number,#}
LIMIT {5,number,#}
