PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX comete: <http://comete.licef.ca/reference#>
PREFIX server: <#>

SELECT DISTINCT ?sWithScore ?location ?format ?added ?updated {4}
WHERE '{'
    ?sWithScore rdf:type <comete:LearningObject> .
    OPTIONAL '{'
        ?sWithScore foaf:page ?location
    '}'
    OPTIONAL '{'
        ?sWithScore dct:format ?format
    '}'
    OPTIONAL '{'
        ?sWithScore comete:added ?added
    '}'
    OPTIONAL '{'
        ?sWithScore comete:updated ?updated
    '}'

{0}

'}'
ORDER BY DESC({1})
OFFSET {2,number,#}
LIMIT {3,number,#}
