PREFIX text: <http://jena.apache.org/text#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT (count(DISTINCT ?s) as ?count) 
WHERE '{'
    '{' ?s text:query ( dcterms:title "{1}" ) '}'
    UNION
    '{' ?s text:query ( dcterms:title "{1}" "lang:{0}" ) '}'
    UNION
    '{' ?s text:query ( dcterms:description "{1}" ) '}'
    UNION
    '{' ?s text:query ( dcterms:description "{1}" "lang:{0}" ) '}'
    UNION
    '{' ?s text:query ( comete:keyword "{1}" ) '}'
    UNION
    '{' ?s text:query ( comete:keyword "{1}" "lang:{0}" ) '}'
    UNION
    '{' ?s text:query ( comete:extraInfo "{1}" ) '}'
    UNION
    '{' ?s text:query ( comete:extraInfo "{1}" "lang:{0}" ) '}'
    UNION
    '{' ?author text:query ( foaf:name "{1}" ) .
        ?s dcterms:creator ?author '}'
    UNION
    '{' ?author text:query ( foaf:name "{1}" "lang:{0}" ) .
        ?s dcterms:creator ?author '}'
    UNION
    '{' ?publisher text:query ( foaf:name "{1}" ) .
        ?s dcterms:publisher ?publisher '}'
    UNION
    '{' ?publisher text:query ( foaf:name "{1}" "lang:{0}" ) .
        ?s dcterms:publisher ?publisher '}'
    UNION
    '{' ?concept text:query ( skos:prefLabel "{1}" ) .
        ?s dcterms:subject ?concept '}'
    UNION
    '{' ?concept text:query ( skos:prefLabel "{1}" "lang:{0}" ) .
        ?s dcterms:subject ?concept '}'
    ?s rdf:type comete:LearningObject
'}'
