PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT ?r ?label
WHERE {
    ?r rdf:type comete:Repository .
    ?r foaf:name ?label
}
ORDER BY ASC(?label)
