PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX comete: <http://comete.licef.ca/reference#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?s ?name
WHERE '{'
    ?s rdf:type <comete:Organization> .
    ?s foaf:name ?name .
    FILTER ( regex( ?name, "{0}", "i" ) )
'}'
OFFSET {1,number,#}
LIMIT {2,number,#}