PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT DISTINCT ?name ?firstname ?lastname ?email ?url ?address ?photo ?tel ?fax ?altname ?altfirstname ?altlastname ?altemail ?alturl ?altaddress ?altphoto ?alttel ?altfax
WHERE '{'
    '{' ?s rdf:type comete:Person '}'
    UNION '{' ?s foaf:name ?name '}' UNION '{' ?s comete:altName ?altname '}'
    UNION '{' ?s foaf:givenName ?firstname '}' UNION '{' ?s comete:altGivenName ?altfirstname '}'
    UNION '{' ?s foaf:familyName ?lastname '}' UNION '{' ?s comete:altFamilyName ?altlastname '}'
    UNION '{' ?s foaf:mbox ?email '}' UNION '{' ?s comete:altMbox ?altemail '}'
    UNION '{' ?s foaf:homepage ?url '}' UNION '{' ?s comete:altHomepage ?alturl '}'
    UNION '{' ?s comete:formattedAddress ?address '}' UNION '{' ?s comete:altFormattedAddress ?altaddress '}'
    UNION '{' ?s foaf:img ?photo '}' UNION '{' ?s comete:altImg ?altphoto '}'
    UNION '{' ?s foaf:phone ?tel . 
              FILTER ( regex(str(?tel), "^tel:") ) '}'
    UNION '{' ?s comete:altPhone ?alttel .
              FILTER ( regex(?alttel, "^tel:") ) '}'
    UNION '{' ?s foaf:phone ?fax .
              FILTER ( regex(str(?fax), "^fax:") ) '}'
    UNION '{' ?s comete:altPhone ?altfax .
              FILTER ( regex(?altfax, "^fax:") ) '}'
    FILTER ( {0} )
}

