PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX comete: <http://comete.licef.ca/reference#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?s
WHERE '{'
    ?s rdf:type comete:Person .
    ?s foaf:mbox <{2}> .
    ?s foaf:givenName|comete:altGivenName "{0}" .
    ?s foaf:familyName|comete:altFamilyName "{1}"
'}'
