PREFIX comete: <http://comete.licef.ca/reference#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?s ?name
WHERE '{'
    ?s rdf:type comete:Organization .
    ?s foaf:name ?name .
    '{'
        ?lo rdf:type comete:LearningObject .
        ?lo (dcterms:creator | dcterms:publisher) ?s
    '}'
    UNION
    '{'
        ?rec rdf:type comete:MetadataRecord .
        ?rec dcterms:creator ?s .
        ?rec comete:describes ?lo
    '}'
'}'
ORDER BY ?name
OFFSET {0,number,#}
LIMIT {1,number,#}
