PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT ?name ?email ?url ?address ?logo ?tel ?fax
WHERE '{'
    '{' ?s rdf:type comete:Organization '}'
    UNION '{' ?s foaf:name ?name '}'
    UNION '{' ?s foaf:mbox ?email '}'
    UNION '{' ?s foaf:homepage ?url '}'
    UNION '{' ?s comete:formattedAddress ?address '}'
    UNION '{' ?s foaf:logo ?logo '}'
    UNION  '{'
        ?s foaf:phone ?tel
        FILTER ( STRSTARTS( STR( ?tel ), "tel:" ) )
    '}'
    UNION '{'
        ?s foaf:phone ?fax
        FILTER ( STRSTARTS( STR( ?fax ), "fax:" ) )
    '}'    
    FILTER ( ?s = <{0}> )    
'}'
