PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT ?s ?n
WHERE '{'
    ?s rdf:type comete:Person .
    ?s org:memberOf <{0}> .
    ?s foaf:name ?n
'}'
