PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT ?s ?p ?o
WHERE '{'
    ?s ?p ?o .
    ?s rdf:type comete:Person .
    FILTER ( ?s = <{0}> &&
             ( ?p = foaf:name || ?p = comete:altName ||
               ?p = foaf:givenName || ?p = comete:altGivenName ||
               ?p = foaf:familyName || ?p = comete:altFamilyName ||
               ?p = foaf:mbox || ?p = comete:altMbox ||
               ?p = comete:formattedAddress || ?p = comete:altFormattedAddress ||
               ?p = foaf:phone || ?p = comete:altPhone ||
               ?p = foaf:homepage || ?p = comete:altHomepage ||
               ?p = foaf:img || ?p = comete:altImg ) ) 
'}'
