PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT DISTINCT ?gid
WHERE {
    ?s rdf:type comete:Organization .
    GRAPH <server:identity-similarity> {
        ?s dct:identifier ?gid
    }    
}