PREFIX comete: <http://comete.licef.ca/reference#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX oai: <http://www.openarchives.org/OAI/2.0/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema>

SELECT ?flag
WHERE '{'
    ?s rdf:type comete:MetadataRecord .
    ?s oai:oai-identifier "{0}" .
    ?s comete:describes ?lo .
    ?lo comete:flag ?flag
'}'
